name: Mirror Repository
on:
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  mirror-gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Push to GitLab
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USER }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ secrets.GITLAB_USER }}/${{ secrets.GITLAB_REPO }}.git
          git push --force gitlab --all
          git push --force gitlab --tags

  mirror-codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Push to Codeberg
        run: |
          git remote add codeberg https://${{ secrets.CODEBERG_USER }}:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/${{ secrets.CODEBERG_USER }}/${{ secrets.CODEBERG_REPO }}.git
          git push --force codeberg --all
          git push --force codeberg --tags